name: Update Netlify Deploy Preview Domain

on:
  push:
    branches:
      - main # або назва вашої основної гілки

jobs:
  update-domain:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Update Deploy Preview Domain
      run: node ./scripts/updateNetlifyDomain.js
      env:
        NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
        SITE_ID: ${{ secrets.SITE_ID }}
        DEPLOY_PREVIEW_CUSTOM_DOMAIN: ${{ secrets.DEPLOY_PREVIEW_CUSTOM_DOMAIN }}
